parameters:
  Environment: String  
  Location: String
  ServiceConnection: String
  FeatureFlag_SQL_StopIfDataLossCanOccur: boolean
  FeatureFlag_SQL_DeployDWH: boolean

stages:
- stage: Stage_${{ parameters.Environment }} 
  displayName: Stage - ${{ parameters.Environment }}
  dependsOn: []
  variables:
    - template: ..\Variables\Variables-Global.yml
  jobs:  

    - template: ..\Jobs\Job-Infrastructure.yml
      parameters: 
        Environment: ${{ parameters.Environment }}  
        Location: ${{ parameters.Location }}
        ServiceConnection: ${{ parameters.ServiceConnection }}



